steps = 8
n_runs = 1
img_path = 'datasets/kipr/images'
data_root = 'exp/linear_probe/kipr'
img_split_path = 'datasets/kipr/splits'
num_cls = 3
unfreeze_clip = False
paper = True
cls_names = ['ClassA', 'ClassB', 'ClassC']
img_ext = '.png'
clip_model = 'ViT-L/14'
lr = 0.001
bs = 128
n_shots = 1
dataset = 'kipr'
